name: Generate Metrics

on:
  workflow_dispatch:      # lets you trigger it manually from the Actions tab
  schedule:
    - cron: "0 0 * * *"  # regenerates once a day
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: pratikkkarn
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_limit: 8
          plugin_habits: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
